apiVersion: v1
kind: ConfigMap
metadata:
  #Name must match the name of the .spec.valuesFrom[0].name in the HelmRelease above
  name: kasten-io-k10-7.5.8-defaults 
  namespace: ${releaseNamespace}
data:
  values.yaml: |-
    ---
    auth:
      tokenAuth:
        enabled: true
    ingress:
      create: true
      class: kommander-traefik
      urlPath: "/kasten"
    prometheus:
      server:
        baseURL: "/kasten/prometheus/"
        prefixURL: "/kasten/prometheus/"
